load('config.js');


function execute() {
    var list = [
        { title: "16+",              input: "/the-loai/16",              script: "gen.js" },
        { title: "18+",              input: "/the-loai/18",              script: "gen.js" },
        { title: "19+",              input: "/the-loai/19",              script: "gen.js" },
        { title: "3D Hentai",        input: "/the-loai/3d-hentai",       script: "gen.js" },
        { title: "Action",           input: "/the-loai/action",          script: "gen.js" },
        { title: "Adult",            input: "/the-loai/adult",           script: "gen.js" },
        { title: "Adventure",        input: "/the-loai/adventure",       script: "gen.js" },
        { title: "Artist CG",        input: "/the-loai/artist-cg",       script: "gen.js" },
        { title: "BDSM",             input: "/the-loai/bdsm",            script: "gen.js" },
        { title: "Big Boobs",        input: "/the-loai/big-boobs",       script: "gen.js" },
        { title: "Bondage",          input: "/the-loai/bondage",         script: "gen.js" },
        { title: "Cheating",         input: "/the-loai/cheating",        script: "gen.js" },
        { title: "Comedy",           input: "/the-loai/comedy",          script: "gen.js" },
        { title: "Comic",            input: "/the-loai/comic",           script: "gen.js" },
        { title: "Doujinshi",        input: "/the-loai/doujinshi",       script: "gen.js" },
        { title: "Drama",            input: "/the-loai/drama",           script: "gen.js" },
        { title: "Ecchi",            input: "/the-loai/ecchi",           script: "gen.js" },
        { title: "Elf",              input: "/the-loai/elf",             script: "gen.js" },
        { title: "Fantasy",          input: "/the-loai/fantasy",         script: "gen.js" },
        { title: "Femdom",           input: "/the-loai/femdom",          script: "gen.js" },
        { title: "Full Color",       input: "/the-loai/full-color",      script: "gen.js" },
        { title: "GangBang",         input: "/the-loai/gangbang",        script: "gen.js" },
        { title: "Gender Bender",    input: "/the-loai/gender-bender",   script: "gen.js" },
        { title: "Harem",            input: "/the-loai/harem",           script: "gen.js" },
        { title: "Hentai",           input: "/the-loai/hentai",          script: "gen.js" },
        { title: "Historical",       input: "/the-loai/historical",      script: "gen.js" },
        { title: "Horror",           input: "/the-loai/horror",          script: "gen.js" },
        { title: "Housewife",        input: "/the-loai/housewife",       script: "gen.js" },
        { title: "Incest",           input: "/the-loai/incest",          script: "gen.js" },
        { title: "Isekai",           input: "/the-loai/isekai",          script: "gen.js" },
        { title: "Lolicon",          input: "/the-loai/lolicon",         script: "gen.js" },
        { title: "Maids",            input: "/the-loai/maids",           script: "gen.js" },
        { title: "MANGA",            input: "/the-loai/manga",           script: "gen.js" },
        { title: "Manhua",           input: "/the-loai/manhua",          script: "gen.js" },
        { title: "Manhwa",           input: "/the-loai/manhwa",          script: "gen.js" },
        { title: "Mature",           input: "/the-loai/mature",          script: "gen.js" },
        { title: "Milf",             input: "/the-loai/milf",            script: "gen.js" },
        { title: "Mind Break",       input: "/the-loai/mind-break",      script: "gen.js" },
        { title: "Mind Control",     input: "/the-loai/mind-control",    script: "gen.js" },
        { title: "Monster",          input: "/the-loai/monster",         script: "gen.js" },
        { title: "Nakadashi",        input: "/the-loai/nakadashi",       script: "gen.js" },
        { title: "Netori",           input: "/the-loai/netori",          script: "gen.js" },
        { title: "NTR",              input: "/the-loai/ntr",             script: "gen.js" },
        { title: "Nurse",            input: "/the-loai/nurse",           script: "gen.js" },
        { title: "Oral",             input: "/the-loai/oral",            script: "gen.js" },
        { title: "Rape",             input: "/the-loai/rape",            script: "gen.js" },
        { title: "Romance",          input: "/the-loai/romance",         script: "gen.js" },
        { title: "School Uniform",   input: "/the-loai/school-uniform",  script: "gen.js" },
        { title: "SchoolGirl",       input: "/the-loai/schoolgirl",      script: "gen.js" },
        { title: "Series",           input: "/the-loai/series",          script: "gen.js" },
        { title: "Shota",            input: "/the-loai/shota",           script: "gen.js" },
        { title: "Shoujo",           input: "/the-loai/shoujo",          script: "gen.js" },
        { title: "Sister",           input: "/the-loai/sister",          script: "gen.js" },
        { title: "Slave",            input: "/the-loai/slave",           script: "gen.js" },
        { title: "Smut",             input: "/the-loai/smut",            script: "gen.js" },
        { title: "Stockings",        input: "/the-loai/stockings",       script: "gen.js" },
        { title: "Supernatural",     input: "/the-loai/supernatural",    script: "gen.js" },
        { title: "Teacher",          input: "/the-loai/teacher",         script: "gen.js" },
        { title: "Tentacles",        input: "/the-loai/tentacles",       script: "gen.js" },
        { title: "Time Stop",        input: "/the-loai/time-stop",       script: "gen.js" },
        { title: "Tình Cảm",         input: "/the-loai/tinh-cam",        script: "gen.js" },
        { title: "Trap",             input: "/the-loai/trap",            script: "gen.js" },
        { title: "Truyện Màu",       input: "/the-loai/truyen-mau",      script: "gen.js" },
        { title: "Truyện tranh 18+", input: "/the-loai/truyen-tranh-18", script: "gen.js" },
        { title: "Truyện Việt",      input: "/the-loai/truyen-viet",     script: "gen.js" },
        { title: "Twins",            input: "/the-loai/twins",           script: "gen.js" },
        { title: "Vampire",          input: "/the-loai/vampire",         script: "gen.js" },
        { title: "Vanilla",          input: "/the-loai/vanilla",         script: "gen.js" },
        { title: "Webtoon",          input: "/the-loai/webtoon",         script: "gen.js" },
        { title: "Yaoi",             input: "/the-loai/yaoi",            script: "gen.js" },
        { title: "Yuri",             input: "/the-loai/yuri",            script: "gen.js" },
    ];
    return Response.success(list);
}